# Site settings
title:          Depth First Learning
email: depthfirstlearning@gmail.com
description:    "Machine Learning Curricula"
url:            "https://www.depthfirstlearning.com"
twitter_username: depthfirstlearning
github_username:  deconstructed

# Authors
dfl:
    name: Depth First Learning
    email: depthfirstlearning@gmail.com
    web: http://twitter.com/DepthFirstLearn
avital:
    name: Avital Oliver
    email: avitalo@google.com
    web: http://twitter.com/avitaloliver
cinjon:
    name: Cinjon Resnick
    email: cinjon.resnick@gmail.com
    web: http://twitter.com/cinjoncin
surya:
    name: Surya Bhupatiraju
    email: sbhupatiraju@google.com
    web: http://twitter.com/suryabhupa
krishna:
    name: Kumar Krishna Agrawal
    email: kumarkagrawal@gmail.com
    web: http://twitter.com/kumarkagrawal
james:
    name: James Allingham
    email: 
    web: https://twitter.com/JamesAllingham
luca:
    name: Luca Venturi
    email: venturi@cims.nyu.edu
    web: https://cims.nyu.edu/~venturi/

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  # - jemoji #Uncomment this to allow emoji in your post
  - jekyll-redirect-from

# Permalinks
permalink:      /:year/:title
paginate:       5
